fix if then else syntax errorw

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -19,10 +19,10 @@ jobs:
         # This step checks the log file for the workflow run and ensures the job succeeded
         run: |
           if grep -q "Step 1 complete!" /path/to/logfile && grep -q "Step 2 complete!" /path/to/logfile; then
-        echo "Job succeeded and emitted the echo statements as expected."
+            echo "Job succeeded and emitted the echo statements as expected."
           else
-        echo "Job failed or did not emit the echo statements as expected."
-        exit 1
+            echo "Job failed or did not emit the echo statements as expected."
+            exit 1
 
   job2:
   # This is job2 which runs a cowsays action
